### ISSUE TITLE
Fix merge conflicts

### ISSUE THREAD

**Issue by chrzyki** [lexibank/mitterhoferbena#13]
https://github.com/lexibank/mitterhoferbena/commit/207bc3a1ffb85093454f24b4a6052ea1a7f540c3 introduced merge conflicts that weren't resolved (e.g. in https://github.com/lexibank/mitterhoferbena/blob/207bc3a1ffb85093454f24b4a6052ea1a7f540c3/CONTRIBUTORS.md).

**Comment by LinguList** [comment]
Ah, can you check this and fix it?

**Comment by chrzyki** [comment]
Yes, will do.
