### ISSUE TITLE
Original wordlist and modifications

### ISSUE THREAD

**Issue by chrzyki** [lexibank/mitterhoferbena#7]
https://github.com/lexibank/mitterhoferbena/blob/master/raw/Wordlist.csv is a modified version of https://github.com/lexibank/mitterhoferbena/blob/master/raw/wordlist.xlsx. Do we keep using `Wordlist.csv` as a base source or do we move these modifications into `cmd_makecldf()`?

**Comment by LinguList** [comment]
I prefer to work from tsv-files, but if you want to open that with some xlsx reader, feel free to to so...

**Comment by chrzyki** [comment]
I just think it is somewhat hard to see what was changed in **raw** between the two files. Not particularly fond of the idea to do that all in code either. Might alleviate the pain a little bit with the changes outsourced to `etc/`.

**Comment by LinguList** [comment]
Keep in mind that this was ALREADY scraped from the students from the book, which was in PDF. So when I then added symbols for missing data in the CSV, this was easier to do manually, than doing other things from XLSX. I think that was mostly what I did, as the XLSX was not perfect. It's the best we can do for now, and for anything more, we'd need the support of those who created their data.

**Comment by chrzyki** [comment]
Ah, okay, makes sense!

**Comment by SimonGreenhill** [comment]
can this be closed?
