### ISSUE TITLE
Updated to pylexibank 2.0

### ISSUE THREAD

**Issue by chrzyki** [lexibank/mitterhoferbena#8]
And another one: https://github.com/lexibank/mitterhoferbena/commit/fd34c38b51b7d954246fc1d8cdf8983a5a6637dd

This tries to be a little bit more concise and circumvents the lingpy & wordlist transformations.

**Comment by LinguList** [comment]
fine with me.

**Comment by SimonGreenhill** [comment]
Looks good, but we can just use this, instead of importing csv.DictReader:

```python
self.raw_dir.read_csv(f, dicts=True, delimiter="\t")
```

**Comment by chrzyki** [comment]
Oh, absolutely! Thanks for the suggestion!

https://github.com/lexibank/mitterhoferbena/commit/1533ac07f4fd26e6e393159872d0efd95d7f3e51

**Comment by SimonGreenhill** [comment]
cool :)
