### ISSUE TITLE
Change in Concepticon list

### ISSUE THREAD

**Issue by CarolinHu** [lexibank/mitterhoferbena#9]
PR 815 over on Concepticon changed one mapping (utensil is now TOOL instead of THING), so this needs to be kept in mind for when the next Concepticon release happens.

**Comment by chrzyki** [comment]
Thanks @CarolinHu, will check!

**Comment by LinguList** [comment]
@chrzyki, once you check, please resolve this issue.

**Comment by chrzyki** [comment]
Will do. I was keeping this on the back-burner for the next Concepticon release, but I can check this immediately as well.

**Comment by chrzyki** [comment]
Updated in https://github.com/lexibank/mitterhoferbena/commit/fb71ea80e0ca8283465b4af4b4d9021f29c10dcf.
